[package]
name = "sf-media"
version = "0.1.0"
edition = "2021"

[dependencies]
sf-core.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "segment_map"
harness = false
